.TH man 1 "26 July 2015" "0.1" "AlxEnum man page"
.SH NAME
AlxEnum \- executes the threshold attack
.SH SYNOPSIS
AlxEnum -i <interface> -p <SSH attack pcap file> -v [verbose?]
.SH DESCRIPTION
AlxEnum
.SH OPTIONS
AlxEnum
.SH SEE ALSO
Nikto(1), Nmap(1), Dirb(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Alexander Van Daele (Xalspacka@gmail.com)